library_sources = files(
  'common/arithmetic.f90',
  'common/math_constants.f90',
  'common/specf.f90',
  'common/string.f90',
  'common/clock.f90',
  'common/display.f90',
  'common/io.f90',
  'basis/spherh.f90',
  'integrals/chebinterp.f90',
  'integrals/boys.f90',
  'integrals/grid/grid_definitions.f90',
  'integrals/grid/LebedevGrid.f90',
  'integrals/THC/thc_definitions.f90',
  'integrals/Auto2e/src/auto2e_BraTransform.f90',
  'integrals/Auto2e/src/auto2e_Hermite.f90',
  'integrals/Auto2e/src/auto2e_KetTransfer.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_10_1.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_10_10.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_10_2.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_10_3.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_10_4.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_10_5.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_10_6.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_10_7.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_10_8.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_10_9.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_2_1.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_2_2.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_3_1.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_3_2.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_3_3.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_4_1.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_4_2.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_4_3.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_4_4.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_5_1.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_5_2.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_5_3.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_5_4.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_5_5.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_6_1.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_6_2.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_6_3.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_6_4.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_6_5_part1.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_6_5_part2.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_6_6_part1.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_6_6_part2.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_6_6_part3.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_7_1.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_7_2.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_7_3.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_7_4.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_7_5.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_7_6.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_7_7.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_8_1.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_8_2.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_8_3.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_8_4.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_8_5.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_8_6.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_8_7.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_8_8.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_9_1.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_9_2.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_9_3.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_9_4.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_9_5.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_9_6.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_9_7.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_9_8.f90',
  'integrals/Auto2e/src/auto2e_KetTransform_9_9.f90',
  'integrals/Auto2e/src/auto2e_SpherTransf.f90',
  'integrals/Auto2e/src/auto2e_WMatrix_part1.f90',
  'integrals/Auto2e/src/auto2e_WMatrix_part2.f90',
  'integrals/Auto2e/src/auto2e_WMatrix_part3.f90',
  'integrals/Auto2e/src/auto2e_eri_dddd.f90',
  'integrals/Auto2e/src/auto2e_eri_dddp.f90',
  'integrals/Auto2e/src/auto2e_eri_ddds.f90',
  'integrals/Auto2e/src/auto2e_eri_ddpp.f90',
  'integrals/Auto2e/src/auto2e_eri_ddps.f90',
  'integrals/Auto2e/src/auto2e_eri_ddss.f90',
  'integrals/Auto2e/src/auto2e_eri_dpdp.f90',
  'integrals/Auto2e/src/auto2e_eri_dpds.f90',
  'integrals/Auto2e/src/auto2e_eri_dppp.f90',
  'integrals/Auto2e/src/auto2e_eri_dpps.f90',
  'integrals/Auto2e/src/auto2e_eri_dpss.f90',
  'integrals/Auto2e/src/auto2e_eri_dsds.f90',
  'integrals/Auto2e/src/auto2e_eri_dspp.f90',
  'integrals/Auto2e/src/auto2e_eri_dsps.f90',
  'integrals/Auto2e/src/auto2e_eri_dsss.f90',
  'integrals/Auto2e/src/auto2e_eri_fddd.f90',
  'integrals/Auto2e/src/auto2e_eri_fddp.f90',
  'integrals/Auto2e/src/auto2e_eri_fdds.f90',
  'integrals/Auto2e/src/auto2e_eri_fdfd.f90',
  'integrals/Auto2e/src/auto2e_eri_fdfp.f90',
  'integrals/Auto2e/src/auto2e_eri_fdfs.f90',
  'integrals/Auto2e/src/auto2e_eri_fdpp.f90',
  'integrals/Auto2e/src/auto2e_eri_fdps.f90',
  'integrals/Auto2e/src/auto2e_eri_fdss.f90',
  'integrals/Auto2e/src/auto2e_eri_ffdd.f90',
  'integrals/Auto2e/src/auto2e_eri_ffdp.f90',
  'integrals/Auto2e/src/auto2e_eri_ffds.f90',
  'integrals/Auto2e/src/auto2e_eri_fffd.f90',
  'integrals/Auto2e/src/auto2e_eri_ffff.f90',
  'integrals/Auto2e/src/auto2e_eri_fffp.f90',
  'integrals/Auto2e/src/auto2e_eri_fffs.f90',
  'integrals/Auto2e/src/auto2e_eri_ffpp.f90',
  'integrals/Auto2e/src/auto2e_eri_ffps.f90',
  'integrals/Auto2e/src/auto2e_eri_ffss.f90',
  'integrals/Auto2e/src/auto2e_eri_fpdd.f90',
  'integrals/Auto2e/src/auto2e_eri_fpdp.f90',
  'integrals/Auto2e/src/auto2e_eri_fpds.f90',
  'integrals/Auto2e/src/auto2e_eri_fpfp.f90',
  'integrals/Auto2e/src/auto2e_eri_fpfs.f90',
  'integrals/Auto2e/src/auto2e_eri_fppp.f90',
  'integrals/Auto2e/src/auto2e_eri_fpps.f90',
  'integrals/Auto2e/src/auto2e_eri_fpss.f90',
  'integrals/Auto2e/src/auto2e_eri_fsdd.f90',
  'integrals/Auto2e/src/auto2e_eri_fsdp.f90',
  'integrals/Auto2e/src/auto2e_eri_fsds.f90',
  'integrals/Auto2e/src/auto2e_eri_fsfs.f90',
  'integrals/Auto2e/src/auto2e_eri_fspp.f90',
  'integrals/Auto2e/src/auto2e_eri_fsps.f90',
  'integrals/Auto2e/src/auto2e_eri_fsss.f90',
  'integrals/Auto2e/src/auto2e_eri_gddd.f90',
  'integrals/Auto2e/src/auto2e_eri_gddp.f90',
  'integrals/Auto2e/src/auto2e_eri_gdds.f90',
  'integrals/Auto2e/src/auto2e_eri_gdfd.f90',
  'integrals/Auto2e/src/auto2e_eri_gdff.f90',
  'integrals/Auto2e/src/auto2e_eri_gdfp.f90',
  'integrals/Auto2e/src/auto2e_eri_gdfs.f90',
  'integrals/Auto2e/src/auto2e_eri_gdgd.f90',
  'integrals/Auto2e/src/auto2e_eri_gdgp.f90',
  'integrals/Auto2e/src/auto2e_eri_gdgs.f90',
  'integrals/Auto2e/src/auto2e_eri_gdpp.f90',
  'integrals/Auto2e/src/auto2e_eri_gdps.f90',
  'integrals/Auto2e/src/auto2e_eri_gdss.f90',
  'integrals/Auto2e/src/auto2e_eri_gfdd.f90',
  'integrals/Auto2e/src/auto2e_eri_gfdp.f90',
  'integrals/Auto2e/src/auto2e_eri_gfds.f90',
  'integrals/Auto2e/src/auto2e_eri_gffd.f90',
  'integrals/Auto2e/src/auto2e_eri_gfff.f90',
  'integrals/Auto2e/src/auto2e_eri_gffp.f90',
  'integrals/Auto2e/src/auto2e_eri_gffs.f90',
  'integrals/Auto2e/src/auto2e_eri_gfgd.f90',
  'integrals/Auto2e/src/auto2e_eri_gfgf.f90',
  'integrals/Auto2e/src/auto2e_eri_gfgp.f90',
  'integrals/Auto2e/src/auto2e_eri_gfgs.f90',
  'integrals/Auto2e/src/auto2e_eri_gfpp.f90',
  'integrals/Auto2e/src/auto2e_eri_gfps.f90',
  'integrals/Auto2e/src/auto2e_eri_gfss.f90',
  'integrals/Auto2e/src/auto2e_eri_ggdd.f90',
  'integrals/Auto2e/src/auto2e_eri_ggdp.f90',
  'integrals/Auto2e/src/auto2e_eri_ggds.f90',
  'integrals/Auto2e/src/auto2e_eri_ggfd.f90',
  'integrals/Auto2e/src/auto2e_eri_ggff.f90',
  'integrals/Auto2e/src/auto2e_eri_ggfp.f90',
  'integrals/Auto2e/src/auto2e_eri_ggfs.f90',
  'integrals/Auto2e/src/auto2e_eri_gggd.f90',
  'integrals/Auto2e/src/auto2e_eri_gggf.f90',
  'integrals/Auto2e/src/auto2e_eri_gggg.f90',
  'integrals/Auto2e/src/auto2e_eri_gggp.f90',
  'integrals/Auto2e/src/auto2e_eri_gggs.f90',
  'integrals/Auto2e/src/auto2e_eri_ggpp.f90',
  'integrals/Auto2e/src/auto2e_eri_ggps.f90',
  'integrals/Auto2e/src/auto2e_eri_ggss.f90',
  'integrals/Auto2e/src/auto2e_eri_gpdd.f90',
  'integrals/Auto2e/src/auto2e_eri_gpdp.f90',
  'integrals/Auto2e/src/auto2e_eri_gpds.f90',
  'integrals/Auto2e/src/auto2e_eri_gpfd.f90',
  'integrals/Auto2e/src/auto2e_eri_gpff.f90',
  'integrals/Auto2e/src/auto2e_eri_gpfp.f90',
  'integrals/Auto2e/src/auto2e_eri_gpfs.f90',
  'integrals/Auto2e/src/auto2e_eri_gpgp.f90',
  'integrals/Auto2e/src/auto2e_eri_gpgs.f90',
  'integrals/Auto2e/src/auto2e_eri_gppp.f90',
  'integrals/Auto2e/src/auto2e_eri_gpps.f90',
  'integrals/Auto2e/src/auto2e_eri_gpss.f90',
  'integrals/Auto2e/src/auto2e_eri_gsdd.f90',
  'integrals/Auto2e/src/auto2e_eri_gsdp.f90',
  'integrals/Auto2e/src/auto2e_eri_gsds.f90',
  'integrals/Auto2e/src/auto2e_eri_gsfd.f90',
  'integrals/Auto2e/src/auto2e_eri_gsff.f90',
  'integrals/Auto2e/src/auto2e_eri_gsfp.f90',
  'integrals/Auto2e/src/auto2e_eri_gsfs.f90',
  'integrals/Auto2e/src/auto2e_eri_gsgs.f90',
  'integrals/Auto2e/src/auto2e_eri_gspp.f90',
  'integrals/Auto2e/src/auto2e_eri_gsps.f90',
  'integrals/Auto2e/src/auto2e_eri_gsss.f90',
  'integrals/Auto2e/src/auto2e_eri_hddd.f90',
  'integrals/Auto2e/src/auto2e_eri_hddp.f90',
  'integrals/Auto2e/src/auto2e_eri_hdds.f90',
  'integrals/Auto2e/src/auto2e_eri_hdfd.f90',
  'integrals/Auto2e/src/auto2e_eri_hdff.f90',
  'integrals/Auto2e/src/auto2e_eri_hdfp.f90',
  'integrals/Auto2e/src/auto2e_eri_hdfs.f90',
  'integrals/Auto2e/src/auto2e_eri_hdgd.f90',
  'integrals/Auto2e/src/auto2e_eri_hdgf.f90',
  'integrals/Auto2e/src/auto2e_eri_hdgg.f90',
  'integrals/Auto2e/src/auto2e_eri_hdgp.f90',
  'integrals/Auto2e/src/auto2e_eri_hdgs.f90',
  'integrals/Auto2e/src/auto2e_eri_hdhd.f90',
  'integrals/Auto2e/src/auto2e_eri_hdhp.f90',
  'integrals/Auto2e/src/auto2e_eri_hdhs.f90',
  'integrals/Auto2e/src/auto2e_eri_hdpp.f90',
  'integrals/Auto2e/src/auto2e_eri_hdps.f90',
  'integrals/Auto2e/src/auto2e_eri_hdss.f90',
  'integrals/Auto2e/src/auto2e_eri_hfdd.f90',
  'integrals/Auto2e/src/auto2e_eri_hfdp.f90',
  'integrals/Auto2e/src/auto2e_eri_hfds.f90',
  'integrals/Auto2e/src/auto2e_eri_hffd.f90',
  'integrals/Auto2e/src/auto2e_eri_hfff.f90',
  'integrals/Auto2e/src/auto2e_eri_hffp.f90',
  'integrals/Auto2e/src/auto2e_eri_hffs.f90',
  'integrals/Auto2e/src/auto2e_eri_hfgd.f90',
  'integrals/Auto2e/src/auto2e_eri_hfgf.f90',
  'integrals/Auto2e/src/auto2e_eri_hfgg.f90',
  'integrals/Auto2e/src/auto2e_eri_hfgp.f90',
  'integrals/Auto2e/src/auto2e_eri_hfgs.f90',
  'integrals/Auto2e/src/auto2e_eri_hfhd.f90',
  'integrals/Auto2e/src/auto2e_eri_hfhf.f90',
  'integrals/Auto2e/src/auto2e_eri_hfhp.f90',
  'integrals/Auto2e/src/auto2e_eri_hfhs.f90',
  'integrals/Auto2e/src/auto2e_eri_hfpp.f90',
  'integrals/Auto2e/src/auto2e_eri_hfps.f90',
  'integrals/Auto2e/src/auto2e_eri_hfss.f90',
  'integrals/Auto2e/src/auto2e_eri_hgdd.f90',
  'integrals/Auto2e/src/auto2e_eri_hgdp.f90',
  'integrals/Auto2e/src/auto2e_eri_hgds.f90',
  'integrals/Auto2e/src/auto2e_eri_hgfd.f90',
  'integrals/Auto2e/src/auto2e_eri_hgff.f90',
  'integrals/Auto2e/src/auto2e_eri_hgfp.f90',
  'integrals/Auto2e/src/auto2e_eri_hgfs.f90',
  'integrals/Auto2e/src/auto2e_eri_hggd.f90',
  'integrals/Auto2e/src/auto2e_eri_hggf.f90',
  'integrals/Auto2e/src/auto2e_eri_hggg.f90',
  'integrals/Auto2e/src/auto2e_eri_hggp.f90',
  'integrals/Auto2e/src/auto2e_eri_hggs.f90',
  'integrals/Auto2e/src/auto2e_eri_hghd.f90',
  'integrals/Auto2e/src/auto2e_eri_hghf.f90',
  'integrals/Auto2e/src/auto2e_eri_hghg.f90',
  'integrals/Auto2e/src/auto2e_eri_hghp.f90',
  'integrals/Auto2e/src/auto2e_eri_hghs.f90',
  'integrals/Auto2e/src/auto2e_eri_hgpp.f90',
  'integrals/Auto2e/src/auto2e_eri_hgps.f90',
  'integrals/Auto2e/src/auto2e_eri_hgss.f90',
  'integrals/Auto2e/src/auto2e_eri_hhdd.f90',
  'integrals/Auto2e/src/auto2e_eri_hhdp.f90',
  'integrals/Auto2e/src/auto2e_eri_hhds.f90',
  'integrals/Auto2e/src/auto2e_eri_hhfd.f90',
  'integrals/Auto2e/src/auto2e_eri_hhff.f90',
  'integrals/Auto2e/src/auto2e_eri_hhfp.f90',
  'integrals/Auto2e/src/auto2e_eri_hhfs.f90',
  'integrals/Auto2e/src/auto2e_eri_hhgd.f90',
  'integrals/Auto2e/src/auto2e_eri_hhgf.f90',
  'integrals/Auto2e/src/auto2e_eri_hhgg.f90',
  'integrals/Auto2e/src/auto2e_eri_hhgp.f90',
  'integrals/Auto2e/src/auto2e_eri_hhgs.f90',
  'integrals/Auto2e/src/auto2e_eri_hhhd.f90',
  'integrals/Auto2e/src/auto2e_eri_hhhf.f90',
  'integrals/Auto2e/src/auto2e_eri_hhhg.f90',
  'integrals/Auto2e/src/auto2e_eri_hhhh.f90',
  'integrals/Auto2e/src/auto2e_eri_hhhp.f90',
  'integrals/Auto2e/src/auto2e_eri_hhhs.f90',
  'integrals/Auto2e/src/auto2e_eri_hhpp.f90',
  'integrals/Auto2e/src/auto2e_eri_hhps.f90',
  'integrals/Auto2e/src/auto2e_eri_hhss.f90',
  'integrals/Auto2e/src/auto2e_eri_hpdd.f90',
  'integrals/Auto2e/src/auto2e_eri_hpdp.f90',
  'integrals/Auto2e/src/auto2e_eri_hpds.f90',
  'integrals/Auto2e/src/auto2e_eri_hpfd.f90',
  'integrals/Auto2e/src/auto2e_eri_hpff.f90',
  'integrals/Auto2e/src/auto2e_eri_hpfp.f90',
  'integrals/Auto2e/src/auto2e_eri_hpfs.f90',
  'integrals/Auto2e/src/auto2e_eri_hpgd.f90',
  'integrals/Auto2e/src/auto2e_eri_hpgf.f90',
  'integrals/Auto2e/src/auto2e_eri_hpgg.f90',
  'integrals/Auto2e/src/auto2e_eri_hpgp.f90',
  'integrals/Auto2e/src/auto2e_eri_hpgs.f90',
  'integrals/Auto2e/src/auto2e_eri_hphp.f90',
  'integrals/Auto2e/src/auto2e_eri_hphs.f90',
  'integrals/Auto2e/src/auto2e_eri_hppp.f90',
  'integrals/Auto2e/src/auto2e_eri_hpps.f90',
  'integrals/Auto2e/src/auto2e_eri_hpss.f90',
  'integrals/Auto2e/src/auto2e_eri_hsdd.f90',
  'integrals/Auto2e/src/auto2e_eri_hsdp.f90',
  'integrals/Auto2e/src/auto2e_eri_hsds.f90',
  'integrals/Auto2e/src/auto2e_eri_hsfd.f90',
  'integrals/Auto2e/src/auto2e_eri_hsff.f90',
  'integrals/Auto2e/src/auto2e_eri_hsfp.f90',
  'integrals/Auto2e/src/auto2e_eri_hsfs.f90',
  'integrals/Auto2e/src/auto2e_eri_hsgd.f90',
  'integrals/Auto2e/src/auto2e_eri_hsgf.f90',
  'integrals/Auto2e/src/auto2e_eri_hsgg.f90',
  'integrals/Auto2e/src/auto2e_eri_hsgp.f90',
  'integrals/Auto2e/src/auto2e_eri_hsgs.f90',
  'integrals/Auto2e/src/auto2e_eri_hshs.f90',
  'integrals/Auto2e/src/auto2e_eri_hspp.f90',
  'integrals/Auto2e/src/auto2e_eri_hsps.f90',
  'integrals/Auto2e/src/auto2e_eri_hsss.f90',
  'integrals/Auto2e/src/auto2e_eri_pppp.f90',
  'integrals/Auto2e/src/auto2e_eri_ppps.f90',
  'integrals/Auto2e/src/auto2e_eri_ppss.f90',
  'integrals/Auto2e/src/auto2e_eri_psps.f90',
  'integrals/Auto2e/src/auto2e_eri_psss.f90',
  'integrals/Auto2e/src/auto2e_eri_ssss.f90',
  'integrals/Auto2e/src/auto2e.f90',
  'basis/sphergto.f90',
  'common/periodic.f90',
  'common/sort.f90',
  'common/sys_definitions.f90',
  'integrals/Cholesky/chol_definitions.f90',
  'integrals/Cholesky/TwoStepCholesky_definitions.f90',
  'linear-algebra/real_linalg.f90',
  'basis/basis_definitions.f90',
  'basis/basis_sets.f90',
  'integrals/Cholesky/sorter_Cholesky.f90',
  'Main/linalg.f90',
  'integrals/Cholesky/TwoStepCholesky_Step1.f90',
  'integrals/Cholesky/TwoStepCholesky_Step2.f90',
  'integrals/Cholesky/TwoStepCholesky.f90',
  'integrals/Cholesky/Cholesky.f90',
  'integrals/OneElectronInts.f90',
  'integrals/grid/GridFunctions.f90',
  'integrals/grid/BeckeGrid.f90',
  'integrals/Multipoles.f90',
  'integrals/THC/TensorHypercontraction.f90',
  'hamiltonian/THCFock.f90',
  'gammcor-interface/Auto2eInterface.f90',
  'gammcor-interface/OneElectronInts_Gammcor.f90',
  'gammcor-interface/THC_Gammcor.f90',
  'gammcor-interface/Cholesky_Gammcor.f90',
)

test_source = files('Main/test.f90')
